name: Backup to GitLab

on:
  push:
    branches:
      - main

env:
  GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Backup to GitLab
      uses: docker://node:8
      env:
        GITLAB_ACCESS_TOKEN: ${{ env.GITLAB_ACCESS_TOKEN }}
      run: |
        git clone https://github.com/mrhavens/mrhavens.co.git
        cd mrhavens.co
        git remote add gitlab https://gitlab-ci-token:$GITLAB_ACCESS_TOKEN@gitlab.com/mrhavens/mrhavens.co.git
        git push gitlab HEAD:master
